### ISSUE TITLE
inner wall for PTD - collate and EDGE issue 

### ISSUE THREAD

**Issue by cespaillat** [danfeldman90/EDGE#20]
I am stuck in an error loop...

In edge.py ....

When I do 

model.dataInit(jobw=406)

I get the error 

IOError: DATAINIT: Job you supplied is not an inner wall or needs to be collated again!

However, it is indeed an inner wall (T=1400), I just ran it with an outer disk because...

In collate.py

when I try to run collate where I just run an inner wall (no matching outer disk) I get the error

IndexError                                Traceback (most recent call last)
<ipython-input-9-92ec9a66e690> in <module>()
----> 1 collate(path, 407, name, path)

/projectnb/bu-disks/scripts/collate.pyc in collate(path, jobnum, name, destination, optthin, clob, high, noextinct, noangle, nowall, nophot, noscatt)
    271 
    272         if noangle == 0:
--> 273             angle = ascii.read(glob(path+'angle_'+name+'_'+jobnum+'_')[0], data_start = 1)
    274             axis['ANGAXIS'] = axis_count
    275 

IndexError: list index out of range

However, if works if I have a matching outer disk.

**Comment by danfeldman90** [comment]
Collate and EDGE should now work for inner walls. In job_file_create(), now set iwall=1 to create a job file where only ISILCOM and IWALLDUST are set to 1. Then when collate runs, you can run a large loop and nothing will crash -- instead, the inner walls will be tagged with the "fail" tag and will show up in failCheck(). To avoid this, collate has to have the angle and extinction correction keywords changed from the default. The fail tag won't screw up EDGE, so you don't have to make it "work flawlessly" if you don't want to.

However, if you want to create inner wall jobs in addition to disk jobs, you either need two separate loops, or you need to add an if statement to differentiate the two, since they have different values for the "iwall" keyword.
